### ISSUE TITLE
[Accordion] Check position of "+" (empty subtitle/title)

### ISSUE THREAD

**Issue by Kostiantyn-Nerubenko** [innocode-digital/wp-block-accordion#2]
![image](https://user-images.githubusercontent.com/26119923/136937131-9c0ae6a7-8a45-4d65-b270-f356c04578df.png)

**Comment by spasea** [comment]
@Kostiantyn-Nerubenko done on stage

**Comment by Kostiantyn-Nerubenko** [comment]
done
